### ISSUE TITLE
auto-py-to-exe

### ISSUE THREAD

**Issue by nrliii** [OpsecGuy/BetterGo#15]
On my pc it worked perfectly the last time i tried compiling into one exe file but now when i use the auto-py-to-exe tool and the output exe i  get an glfw3 error

```
Traceback (most recent call last):
  File "app.py", line 6, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "gui.py", line 5, in <module>
    import random, time, overlay
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "overlay.py", line 5, in <module>
    from glfw import init, window_hint, create_window, set_input_mode, make_context_current, swap_interval, swap_buffers, \
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "glfw\__init__.py", line 43, in <module>
ImportError: Failed to load GLFW3 shared library.
```

**Comment by OpsecGuy** [comment]
Hey,
You need to include pre-compiled binaries of GLFW3.
You can download it from https://www.glfw.org/download.html
