### ISSUE TITLE
name 'window_name' is not defined  and Could not read memory 

### ISSUE THREAD

**Issue by liuliming2008** [OpsecGuy/BetterGo#17]
python app.py
name 'window_name' is not defined
name 'window_name' is not defined
Could not read memory at: 12218, length: 2 - GetLastError: 299
Could not read memory at: 12218, length: 2 - GetLastError: 299
Could not read memory at: 12218, length: 2 - GetLastError: 299

**Comment by thatoneguy-hun** [comment]
py app.py

name 'window_name' is not defined
name 'window_name' is not defined
Exception in thread opengl_overlay:
Traceback (most recent call last):
  File "C:\Users\Rendszer\AppData\Local\Programs\Python\Python39\lib\site-packages\pymem\__init__.py", line 530, in read_int
    value = pymem.memory.read_int(self.process_handle, address)
  File "C:\Users\Rendszer\AppData\Local\Programs\Python\Python39\lib\site-packages\pymem\memory.py", line 304, in read_int
    bytes = read_bytes(handle, address, struct.calcsize('i'))
  File "C:\Users\Rendszer\AppData\Local\Programs\Python\Python39\lib\site-packages\pymem\memory.py", line 105, in read_bytes
    raise pymem.exception.WinAPIError(error_code)
pymem.exception.WinAPIError: Windows api error, error_code: 299

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Rendszer\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\Rendszer\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Rendszer\OneDrive\Asztali gép\BetterGo-main\app.py", line 533, in opengl_overlay
    dx = (ScreenSize.x + 1) / lp.get_fov()
  File "C:\Users\Rendszer\OneDrive\Asztali gép\BetterGo-main\local.py", line 65, in get_fov
    return self.mem.game_handle.read_int(self.local_player() + offsets.m_iDefaultFOV)
  File "C:\Users\Rendszer\AppData\Local\Programs\Python\Python39\lib\site-packages\pymem\__init__.py", line 532, in read_int
    raise pymem.exception.MemoryReadError(address, struct.calcsize('i'), e.error_code)
pymem.exception.MemoryReadError: Could not read memory at: 13116, length: 4 - GetLastError: 299

then crashes in 3-5 minutes

**Comment by OpsecGuy** [comment]
That case is under investigation.

**Comment by OpsecGuy** [comment]
https://github.com/OpsecGuy/BetterGo/issues/21
