### ISSUE TITLE
Don't work for me | Could not open process: ******

### ISSUE THREAD

**Issue by HattoriHanzuo** [OpsecGuy/BetterGo#18]
Hey Hey. 

I did everything according to the instructions.

Unfortunately, I get the following error message.

`
[notice] A new release of pip available: 22.3.1 -> 23.0
[notice] To update, run: python.exe -m pip install --upgrade pip

C:\Users\Sven\Desktop\_TEMP\_GO_Better_CSGO>
C:\Users\Sven\Desktop\_TEMP\_GO_Better_CSGO>
C:\Users\Sven\Desktop\_TEMP\_GO_Better_CSGO>py -m pip install --upgrade pip
Requirement already satisfied: pip in c:\users\sven\appdata\local\programs\python\python310\lib\site-packages (22.3.1)
Collecting pip
  Downloading pip-23.0-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 5.7 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.3.1
    Uninstalling pip-22.3.1:
      Successfully uninstalled pip-22.3.1
Successfully installed pip-23.0

C:\Users\Sven\Desktop\_TEMP\_GO_Better_CSGO>py app.py
Traceback (most recent call last):
  File "C:\Users\Sven\Desktop\_TEMP\_GO_Better_CSGO\app.py", line 3, in <module>
    from memory import *
  File "C:\Users\Sven\Desktop\_TEMP\_GO_Better_CSGO\memory.py", line 9, in <module>
    game_handle = Pymem('csgo.exe')
  File "C:\Users\Sven\AppData\Local\Programs\Python\Python310\lib\site-packages\pymem\__init__.py", line 44, in __init__    self.open_process_from_name(process_name)
  File "C:\Users\Sven\AppData\Local\Programs\Python\Python310\lib\site-packages\pymem\__init__.py", line 204, in open_process_from_name
    self.open_process_from_id(self.process_id)
  File "C:\Users\Sven\AppData\Local\Programs\Python\Python310\lib\site-packages\pymem\__init__.py", line 226, in open_process_from_id
    raise pymem.exception.CouldNotOpenProcess(self.process_id)
pymem.exception.CouldNotOpenProcess: Could not open process: 24328

C:\Users\Sven\Desktop\_TEMP\_GO_Better_CSGO>py app.py
Traceback (most recent call last):
  File "C:\Users\Sven\Desktop\_TEMP\_GO_Better_CSGO\app.py", line 3, in <module>
    from memory import *
  File "C:\Users\Sven\Desktop\_TEMP\_GO_Better_CSGO\memory.py", line 9, in <module>
    game_handle = Pymem('csgo.exe')
  File "C:\Users\Sven\AppData\Local\Programs\Python\Python310\lib\site-packages\pymem\__init__.py", line 44, in __init__    self.open_process_from_name(process_name)
  File "C:\Users\Sven\AppData\Local\Programs\Python\Python310\lib\site-packages\pymem\__init__.py", line 204, in open_process_from_name
    self.open_process_from_id(self.process_id)
  File "C:\Users\Sven\AppData\Local\Programs\Python\Python310\lib\site-packages\pymem\__init__.py", line 226, in open_process_from_id
    raise pymem.exception.CouldNotOpenProcess(self.process_id)
pymem.exception.CouldNotOpenProcess: Could not open process: 24328

C:\Users\Sven\Desktop\_TEMP\_GO_Better_CSGO>py app.py
Traceback (most recent call last):
  File "C:\Users\Sven\Desktop\_TEMP\_GO_Better_CSGO\app.py", line 3, in <module>
    from memory import *
  File "C:\Users\Sven\Desktop\_TEMP\_GO_Better_CSGO\memory.py", line 9, in <module>
    game_handle = Pymem('csgo.exe')
  File "C:\Users\Sven\AppData\Local\Programs\Python\Python310\lib\site-packages\pymem\__init__.py", line 44, in __init__    self.open_process_from_name(process_name)
  File "C:\Users\Sven\AppData\Local\Programs\Python\Python310\lib\site-packages\pymem\__init__.py", line 204, in open_process_from_name
    self.open_process_from_id(self.process_id)
  File "C:\Users\Sven\AppData\Local\Programs\Python\Python310\lib\site-packages\pymem\__init__.py", line 226, in open_process_from_id
    raise pymem.exception.CouldNotOpenProcess(self.process_id)
pymem.exception.CouldNotOpenProcess: Could not open process: 24328

C:\Users\Sven\Desktop\_TEMP\_GO_Better_CSGO>
`

Another question is: Is it still safe to use? Is it updated?

**Comment by OpsecGuy** [comment]
Hey, please use newest version that has been published yesterday.

Yes, it's safe to use, if you need to be extra safe don't use features market by '?'.
