### ISSUE TITLE
i dont know if its me being a total retard but i get this error

### ISSUE THREAD

**Issue by Vipqix** [OpsecGuy/BetterGo#24]
```
Exception in thread opengl_overlay:
Traceback (most recent call last):
  File "C:\Users\vipqix\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\vipqix\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\vipqix\BetterGo\app.py", line 539, in opengl_overlay
    ov = Overlay()
         ^^^^^^^^^
  File "C:\Users\vipqix\BetterGo\overlay.py", line 16, in __init__
    if not glfw.init() or not glut.glutInit():
                              ^^^^^^^^^^^^^^^
  File "C:\Users\vipqix\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenGL\GLUT\special.py", line 333, in glutInit
    _base_glutInit( ctypes.byref(count), holder )
  File "C:\Users\vipqix\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenGL\platform\baseplatform.py", line 423, in __call__
    raise error.NullFunctionError(
OpenGL.error.NullFunctionError: Attempt to call an undefined function glutInit, check for bool(glutInit) before calling
```

**Comment by OpsecGuy** [comment]
Please refer to this
https://i.imgur.com/Jr42wgW.png
