### ISSUE TITLE
Error while launch

### ISSUE THREAD

**Issue by kolegorm** [OpsecGuy/BetterGo#4]
Traceback (most recent call last):
  File "C:\Users\Binaryx\BetterG\app.py", line 5, in <module>
    from memory import *
  File "C:\Users\Binaryx\BetterG\memory.py", line 8, in <module>
    client_dll = process.module_from_name(game_handle.process_handle, 'client.dll').lpBaseOfDll
AttributeError: 'NoneType' object has no attribute 'lpBaseOfDll'

**Comment by OpsecGuy** [comment]
Same issue occurs with new version of program?

**Comment by gr1ndy** [comment]
did u install the requirements?

1. open cmd and cd to the directory where requirements.txt is located.
2. run: pip install -r requirements.txt.
