### ISSUE TITLE
App.py not working.

### ISSUE THREAD

**Issue by lonto1001** [OpsecGuy/BetterGo#40]
Error i get (i belive its a error)

C:\Users\me\Desktop\BetterGo-main>py app.py
Traceback (most recent call last):
  File "C:\Users\me\Desktop\BetterGo-main\app.py", line 3, in <module>
    from memory import *
  File "C:\Users\me\Desktop\BetterGo-main\memory.py", line 1, in <module>
    import os, time, ctypes, win32process, win32con, win32event, win32gui, sys, struct
ModuleNotFoundError: No module named 'win32process'

**Comment by lonto1001** [comment]
Updated python reestarted my pc reinstaled setup.txt and now it works.
